### ISSUE TITLE
Certificate creation script doesn't support directories containing space

### ISSUE THREAD

**Issue by altostratous** [SharifAIChallenge/game_runner#14]
This command would lead to bad things.

      ./game_runner/scripts/secure_docker_start_registry.sh localhost

**Comment by akmohtashami** [comment]
I think it's better if we add some configure script which creates the certificates and configures the scripts to use them (maybe embedding them in the scripts to allow easy transportation of scripts for example make-me-big.sh). This would remove the need to be in the same place as scripts when running them.
